//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniowyPB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Zakupy = new HashSet<Zakupy>();
        }
    
        public int SamochodID { get; set; }
        public string Model { get; set; }
        public int RokProdukcji { get; set; }
        public string NumerSeryjny { get; set; }
        public string WersjaWyposazenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakupy> Zakupy { get; set; }
    }
}
