//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniowyPB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektZaliczeniowyBazaSamochodowEntities : DbContext
    {
        public ProjektZaliczeniowyBazaSamochodowEntities()
            : base("name=ProjektZaliczeniowyBazaSamochodowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Polisy> Polisy { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Samochody> Samochody { get; set; }
        public virtual DbSet<Wydzialy> Wydzialy { get; set; }
        public virtual DbSet<Zakupy> Zakupy { get; set; }
    }
}
