//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniowyPB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakupy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakupy()
        {
            this.Polisy = new HashSet<Polisy>();
        }
    
        public int ZakupID { get; set; }
        public System.DateTime DataZakupu { get; set; }
        public int KlientID { get; set; }
        public int PracownikID { get; set; }
        public int SamochodID { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polisy> Polisy { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}
